### ISSUE TITLE
[BUG] Package 'ms' not found in deploy actions.

### ISSUE THREAD

**Issue by semikernel** [jeertmans/manim-slides-starter#1]
When I try to use manim-slides-starter. my deploy proceeding encountered an error. It said:
```bash
| PackageNotFound: Some packages not found in the repository
|     at Object.install (setup-texlive-action/v3/packages/texlive/src/tlmgr/actions/install.ts:35:13)
|     at setup-texlive-action/v3/packages/action/src/runs/main/index.ts:74:7 {
|   action: 'install',
|   packages: [
|     'ms'
|   ]
| }
Error: PackageNotFound: Some packages not found in the repository
```
Should I update the Tex version or do anything else, could you please give me a hint, thx a lot!
![image](https://github.com/jeertmans/manim-slides-starter/assets/124420696/a7babc19-3074-4bce-a9f3-c5c97a5cc7c8)

**Comment by jeertmans** [comment]
Nice catch @semikernel! It looks like this package was removed in a recent version of TeXLive, so #2 should fix this.
