### ISSUE TITLE
Plenty of Tex issues when using the template.

### ISSUE THREAD

**Issue by semikernel** [jeertmans/manim-slides-starter#3]
I kept receiving errors when I used the template to render the three Scene: Introduction WithTeX and Outro.
These error looks like [these lines](https://github.com/semikernel/ReportSlides.github.io/actions/runs/9754791513/workflow#:~:text=%2D%20name%3A%20Setup,xkeyval) doesn't work.
The errors are like these:
```bash
  LaTeX Error: File  standalone.cls' not found. 
```
 This is the first error I got. Then I install texlive-latex-extra and copy standalone.cls file locally to fix it.  
```bash
 - name: Install TeX Live and extra packages
     run: |
        sudo apt-get update
        sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended
- name: Copy standalone.cls
      run: |
        cp tex/standalone.cls /usr/share/texlive/texmf-dist/tex/latex/base/standalone.cls
```
Then I got another error:
```bash
  LaTeX Error: File    preview.sty' not found.  
```
I copied the file preview.sty like what I done with standalone. It looks like:
```bash
 - name: Create directory for preview.sty
      run: |
        sudo mkdir -p /usr/share/texlive/texmf-dist/tex/latex/preview
- name: Copy preview.sty
      run: |
        sudo cp preview.sty /usr/share/texlive/texmf-dist/tex/latex/preview/preview.sty
```
After that, I got another error:
```bash
ValueError: Your installation does not support converting .dvi files to SVG. 
Consider updating dvisvgm to at least version 2.4. If this does not solve the 
problem, please refer to our troubleshooting guide at: 
https://docs.manim.community/en/stable/faq/general.html#my-installation-does-not
-support-converting-pdf-to-svg-help
```
Then I try to install dvisvgm:
```bash
- name: Install dvisvgm from source
      run: |
        sudo apt-get install -y cmake gcc g++ libkpathsea-dev libpotrace-dev
        wget http://dvisvgm.de/uploads/tx_sfbooks/dvisvgm-2.4.tar.gz
        tar -xzf dvisvgm-2.4.tar.gz
        cd dvisvgm-2.4
        ./configure
        make
        sudo make install
        cd ..
        rm -rf dvisvgm-2.4 dvisvgm-2.4.tar.gz
```
However, it can't install dvisvgm:
```bash
Connecting to dvisvgm.de (dvisvgm.de)|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-07-02 04:05:59 ERROR 404: Not Found.
Error: Process completed with exit code 8.
```
I wanted to deploy the manim-slides-starter in my own repo.
 **Luckily, if I only render the **Introduction** slide, it work.**
Could you please indicate the possible solution to configure the Tex correctly? Thx a lot! 
The repo is here: [link](https://github.com/semikernel/ReportSlides.github.io)

**Comment by jeertmans** [comment]
Hello! This is weird, but I think you should not need to install the LaTeX packages other than with the action. And what is weird is that standalone should be installed. I won’t have access to a computer until mid of July, but can you reset the workflow file to match that of this repository? Then send me the workflow run log link :)

**Comment by semikernel** [comment]
> Hello! This is weird, but I think you should not need to install the LaTeX packages other than with the action. And what is weird is that standalone should be installed. I won’t have access to a computer until mid of July, but can you reset the workflow file to match that of this repository? Then send me the workflow run log link :)

[This the link to the log after the ms replaced by a list of packages but no other more changes](https://productionresultssa18.blob.core.windows.net/actions-results/54858fbd-d5c3-4082-aff8-79b0a3a423a0/workflow-job-run-e07742bd-189a-5079-918b-43f8b2f94b89/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-07-03T01%3A23%3A13Z&sig=Wrii0A10%2BjSvcCmMBliOqqOhiks%2FL%2Bl5v3L0%2F6CtAa0%3D&ske=2024-07-03T09%3A14%3A50Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-07-02T21%3A14%3A50Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2023-11-03&sp=r&spr=https&sr=b&st=2024-07-03T01%3A13%3A08Z&sv=2023-11-03)
[This is the link to the workflow file it used](https://github.com/semikernel/ReportSlides.github.io/actions/runs/9741744243/workflow#:~:text=%23%20Simple%20workflow,%24%7B%7B%20secrets.GITHUB_TOKEN%20%7D%7D)
[This is the link to the slides.py](https://raw.githubusercontent.com/semikernel/ReportSlides.github.io/main/slides.py)
By the way, I think it's more convenient to render the scenes locally and then update them to the github-pages. Thank you again for your guidance!
(ps: I found that the repo name must be _______.github.io so that github pages will work well, the suffix is necessary.)

**Comment by jeertmans** [comment]
> > Hello! This is weird, but I think you should not need to install the LaTeX packages other than with the action. And what is weird is that standalone should be installed. I won’t have access to a computer until mid of July, but can you reset the workflow file to match that of this repository? Then send me the workflow run log link :)
> 
> [This the link to the log after the ms replaced by a list of packages but no other more changes](https://productionresultssa18.blob.core.windows.net/actions-results/54858fbd-d5c3-4082-aff8-79b0a3a423a0/workflow-job-run-e07742bd-189a-5079-918b-43f8b2f94b89/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-07-03T01%3A23%3A13Z&sig=Wrii0A10%2BjSvcCmMBliOqqOhiks%2FL%2Bl5v3L0%2F6CtAa0%3D&ske=2024-07-03T09%3A14%3A50Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-07-02T21%3A14%3A50Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2023-11-03&sp=r&spr=https&sr=b&st=2024-07-03T01%3A13%3A08Z&sv=2023-11-03) [This is the link to the workflow file it used](https://github.com/semikernel/ReportSlides.github.io/actions/runs/9741744243/workflow#:~:text=%23%20Simple%20workflow,%24%7B%7B%20secrets.GITHUB_TOKEN%20%7D%7D) [This is the link to the slides.py](https://raw.githubusercontent.com/semikernel/ReportSlides.github.io/main/slides.py) By the way, I think it's more convenient to render the scenes locally and then update them to the github-pages. Thank you again for your guidance!

Hello @semikernel! Very sorry for the late reply, I was on holidays, and then I forgot to check. Reading your config files (both action workflow and `slides.py`), they look the same as the ones from the template. But the link to the logs seems broken (maybe I don't have the access). Can you try creating another repository from the template, and just check if the action runs successfully (without any change)?

> (ps: I found that the repo name must be _______.github.io so that github pages will work well, the suffix is necessary.)

I don't think that's necessary at all. The only "special" repository is `<you-username>.github.io` and it will render any `index.html` at `https://<your-ursername>.github.io`. Other repository names will render their content at `https://<your-ursername>.github.io/<repository-name>`. At least, this is how it works for my repositories.

**Comment by jeertmans** [comment]
I think this was fixed recently with https://github.com/jeertmans/manim-slides/releases/tag/v5.1.9, so I am closing this issue, but feel free to re-open if it persists.
